trigger:
  branches:
    include:
      - main
      - prepare-release/*
  paths:
    include:
      - TMF

name: '[Build and Deploy] Tenant Management Framework'

variables:
  major: 1
  minor: 3
  patch: $(Build.BuildID)
  moduleName: 'TMF'
  releaseFeed: 'vwgs-azdevops-release'
  buildVer: $(major).$(minor).$(Build.BuildID)
  ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
    prerelease: prerelease
    nugetVer: $(buildVer)-$(prerelease)
  ${{ else }}:
    nugetVer: $(buildVer)

pool:
  vmImage: "ubuntu-latest"

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - task: PowerShell@2
      displayName: Updating module manifest
      inputs:
        filePath: 'build/build.ps1'
        arguments: '-ModuleName $(moduleName) -BuildVersion $(buildVer) -LicenseUri $(licenseUri) -ProjectUri $(projectUri) -Tags $(tags) -Prerelease $(prerelease)'
    - task: CopyFiles@2
      displayName: Adding LICENSE to module
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: 'LICENSE'
        TargetFolder: '$(System.DefaultWorkingDirectory)/TMF'
    - task: NuGetCommand@2
      displayName: Building NuGet package
      inputs:
        command: 'pack'
        packagesToPack: '$(System.DefaultWorkingDirectory)/$(moduleName)/$(moduleName).nuspec'
        versioningScheme: byEnvVar
        versionEnvVar: nugetVer
        buildProperties: 'VERSIONHERE=$(nugetVer)'    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'package'
        publishLocation: 'Container'
- stage: publish_gallery
  jobs:
  - job: publish
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'package'
          itemPattern: '**'
          targetPath: '$(Pipeline.Workspace)'
      - task: PowerShell@2
        displayName: Publishing module to Powershell Gallery
        inputs:
          filePath: 'build/publish.ps1'
          arguments: '-ModuleName $(moduleName) -ArtifactPath $(Pipeline.Workspace) -ApiKey $(apiKey)'
- stage: publish_internal_feed
  jobs:
  - job: publish
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'package'
          itemPattern: '**'
          targetPath: '$(Pipeline.Workspace)'
      - task: NuGetCommand@2
        displayName: Publishing module to internal NuGet feed
        inputs:
          command: 'push'
          packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: 'Azure Team VWGS/vwgs-azdevops-release'
          allowPackageConflicts: true