trigger:
- main
- prepare-release/*

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    git remote add --mirror=fetch target https://$(githubPAT)@github.com/ATVWGS/tenant-management-framework.git
    git fetch origin
    git push target HEAD:$(Build.SourceBranchName)
  displayName: 'Push to github'