trigger:
- main
- prepare-release/*

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    git push --force --prune https://$(githubPAT)@github.com/ATVWGS/tenant-management-framework.git refs/heads/$(Build.SourceBranchName)
  displayName: 'Push to github'