trigger:
- main
- prepare-release/*

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    git remote add --mirror=fetch target https://$(githubPAT)@github.com/ATVWGS/tenant-management-framework.git
    git push --tags target HEAD:$(Build.SourceBranch)
  displayName: 'Push to github'